name: git-push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: git push origin `echo $GITHUB_REF|sed 's+refs/heads/++'`
